POST http://localhost:3001/api/blogs
Content-Type: application/json 

{
"title": "Test",
"author": "Yomero",
"url": "www.blog.com",
"likes": 23,
"userId": "66fd868c280ce8e59c877cee"
}

### 

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RpbmdVc2VyIiwiaWQiOiI2NmZkODY4YzI4MGNlOGU1OWM4NzdjZWUiLCJpYXQiOjE3Mjc4OTIyNTR9.huwrBjTHb3luyYlhXdy3aA5Dbko8-r36bpTEOOD2Dr4

{
"title": "How to use JWT Tokens",
"author": "YomeroPalomero",
"url": "www.blog.com",
"likes": 29,
"userId": "66fd868c280ce8e59c877cee"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RpbmdVc2VyIiwiaWQiOiI2NmZkODY4YzI4MGNlOGU1OWM4NzdjZWUiLCJpYXQiOjE3Mjc4OTIyNTR9.huwrBjTHb3luyYlhXdy3aA5Dbko8-r36bpTEOOD2Dr4

{
"title": "I will delete this",
"author": "YomeroPalomero",
"url": "www.blog.com",
"likes": 29,
"userId": "66fd868c280ce8e59c877cee"
}